### ISSUE TITLE
Vibration does not work when app is not active on Android 8

### ISSUE THREAD

**Issue by Creiger** [apache/cordova-plugin-vibration#71]
On Android 7, it was possible to send vibration from the app that was not active. This is not possible anymore on Android 8. Could this be fixed?

**Comment by jcesarmobile** [comment]
The plugin removed all android native code because it was possible to do it with browser APIs, but then a new Chrome version was released that don't allow to vibrate if there is no user interaction.
A similar issue was created on JIRA and the decision was to do nothing about it.
So you'll have to create your own plugin that does native vibration
